"""Add image field to Posts

Revision ID: 45df7ae25189
Revises: 3e6d47cd34fb
Create Date: 2025-05-26 23:13:36.875092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45df7ae25189'
down_revision = '3e6d47cd34fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
